export const fonts = {
  bodyRegular: 'HankenGrotesk_400Regular',
  bodyMedium: 'HankenGrotesk_500Medium',
  bodySemiBold: 'HankenGrotesk_600SemiBold',
  bodyBold: 'HankenGrotesk_700Bold',
  displayRegular: 'Newsreader_400Regular',
  displayItalic: 'Newsreader_400Regular_Italic',
  displayMedium: 'Newsreader_500Medium',
  displayMediumItalic: 'Newsreader_500Medium_Italic',
  captionSerif: 'PlayfairDisplay_400Regular',
  captionSerifMedium: 'PlayfairDisplay_500Medium',
  script: 'ThenScript_400Regular',
  scriptMedium: 'ThenScript_500Medium',
  scriptBold: 'ThenScript_700Bold',
  signature: 'ThenSignature_400Regular',
  cameraRegular: 'CourierPrime_400Regular',
  cameraBold: 'CourierPrime_700Bold',
} as const;
